stages:
  - build_and_push

variables:
  GO_VERSION: 1.16
  REPO_NAME: kpipe/memtest
  TAG: latest

build_and_push:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: build_and_push
  script:
    - apk add --no-cache git
    - docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - docker build -t $REPO_NAME:$TAG .
    - docker push $REPO_NAME:$TAG
